# Form implementation generated from reading ui file '0012_Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(436, 445)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_first = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_first.setFont(font)
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.horizontalLayout.addWidget(self.lineEdit_first)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_second = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_second.setFont(font)
        self.lineEdit_second.setObjectName("lineEdit_second")
        self.horizontalLayout_2.addWidget(self.lineEdit_second)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_add = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_3.addWidget(self.pushButton_add)
        self.pushButton_minus = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.horizontalLayout_3.addWidget(self.pushButton_minus)
        self.pushButton_mult = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.pushButton_mult.setFont(font)
        self.pushButton_mult.setObjectName("pushButton_mult")
        self.horizontalLayout_3.addWidget(self.pushButton_mult)
        self.pushButton_div = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.horizontalLayout_3.addWidget(self.pushButton_div)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_result = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_4.addWidget(self.label_result)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        # Calculator Add, Subtract, divide, mult handlers
        self.pushButton_add.clicked.connect(self.add)
        self.pushButton_minus.clicked.connect(self.subtract)
        self.pushButton_mult.clicked.connect(self.multiply)
        self.pushButton_div.clicked.connect(self.divide)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def add(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        result = fnum + secnum
        self.label_result.setText("Addition : {}".format(result))

    def subtract(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        result = fnum - secnum
        self.label_result.setText("Subtraction : {}".format(result))

    def divide(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        result = 0
        if secnum == 0:
            result = "You can't divide by zero, Willy Wonka"
        else:
            result = fnum / secnum


        self.label_result.setText("Division : {}".format(result))

    def multiply(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        result = fnum * secnum
        self.label_result.setText("Multiply : {}".format(result))



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TOCYWEN"))
        self.label_3.setText(_translate("Form", "The Only Calculator you will ever need!"))
        self.label_4.setText(_translate("Form", "TOCYWEN"))
        self.label.setText(_translate("Form", "1st Number:"))
        self.lineEdit_first.setPlaceholderText(_translate("Form", "Please enter 1st number"))
        self.label_2.setText(_translate("Form", "2nd Number:"))
        self.lineEdit_second.setPlaceholderText(_translate("Form", "Please enter 2nd number"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_mult.setText(_translate("Form", "*"))
        self.pushButton_div.setText(_translate("Form", "/"))
        self.label_result.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
