# Form implementation generated from reading ui file 'WindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QTDesignerExample(object):
    def setupUi(self, QTDesignerExample):
        QTDesignerExample.setObjectName("QTDesignerExample")
        QTDesignerExample.resize(787, 380)

        self.retranslateUi(QTDesignerExample)
        QtCore.QMetaObject.connectSlotsByName(QTDesignerExample)

    def retranslateUi(self, QTDesignerExample):
        _translate = QtCore.QCoreApplication.translate
        QTDesignerExample.setWindowTitle(_translate("QTDesignerExample", "QT Designer Example"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QTDesignerExample = QtWidgets.QWidget()
    ui = Ui_QTDesignerExample()
    ui.setupUi(QTDesignerExample)
    QTDesignerExample.show()
    sys.exit(app.exec())
